FROM quay.io/keycloak/keycloak:latest as builder
#ENV KC_HEALTH_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_METRICS_ENABLED=true
#ENV KC_HTTP_RELATIVE_PATH="/auth"
# Install custom providers
# Apple Social Identity Provider - https://github.com/klausbetz/apple-identity-provider-keycloak
ADD --chown=keycloak:keycloak https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.10.0/apple-identity-provider-1.10.0.jar /opt/keycloak/providers/apple-identity-provider-1.10.0.jar
# FITP Enricher
ADD --chown=keycloak:keycloak https://github.com/HiWay-Media/keycloak-fitp-enricher/releases/download/v0.1.0/fitp-enricher-1.0.0.jar /opt/keycloak/providers/fitp-enricher-1.0.0.jar
#
# build optimized image
RUN ls -l /opt/keycloak/providers/ && /opt/keycloak/bin/kc.sh build
#
RUN /opt/keycloak/bin/kc.sh build 
#
#
FROM quay.io/keycloak/keycloak:latest
WORKDIR /opt/keycloak
COPY --from=builder /opt/keycloak/ /opt/keycloak/
RUN /opt/keycloak/bin/kc.sh build 
#
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
#